Change ssh agent

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,12 +32,29 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
 
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY }}
+          aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_KEY }}
+          aws-region: ${{ secrets.EC2_REGION }}
+      - name: Get runner IP Address
+        id: ip
+        uses: haythem/public-ip@v1.2
+      - name: Whitelist runner IP Address
+        run: |
+          aws ec2 authorize-security-group-ingress \
+            --group-id ${{ secrets.EC2_SG_ID }} \
+            --protocol tcp \
+            --port 22 \
+            --cidr ${{ steps.ip.outputs.ipv4 }}/32
+
       - name: Deploy and Build on EC2
         run: |
-          set -e  # Exit on error
           echo "Copying files to the EC2 instance..."
+          echo $PWD
           # Copy all files to the EC2 instance
-          scp -o StrictHostKeyChecking=no -r . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_DEPLOY_PATH }} || { echo "Failed to copy files"; exit 1; }
+          scp -o StrictHostKeyChecking=no -r $PWD ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_DEPLOY_PATH }} || { echo "Failed to copy files"; exit 1; }
 
           echo "Connecting via SSH and building the Docker container..."
           # Connect via SSH and build, stop, remove, and run the new container
@@ -53,3 +70,11 @@ jobs:
             echo "Running new container..."
             docker run -d -p 443:8000 --name prod jwind/spendlog-api || { echo "Failed to run Docker container"; exit 1; }
           EOF
+
+      - name: Revoke runner IP Address
+        run: |
+          aws ec2 revoke-security-group-ingress \
+            --group-id ${{ secrets.EC2_SG_ID }} \
+            --protocol tcp \
+            --port 22 \
+            --cidr ${{ steps.ip.outputs.ipv4 }}/32
